export const SOUND_PACMAN_BEGINNING = new AudioClip("sounds/pacman_beginning.mp3")
export const SOUND_PACMAN_CHOMP = new AudioClip("sounds/pacman_chomp.mp3")
export const SOUND_PACMAN_DEATH = new AudioClip("sounds/pacman_death.mp3")
export const SOUND_PACMAN_EAT_FRUIT = new AudioClip("sounds/pacman_eatfruit.mp3")
export const SOUND_PACMAN_EAT_GHOST = new AudioClip("sounds/pacman_eatghost.mp3")
export const SOUND_PACMAN_EXTRA_PAC = new AudioClip("sounds/pacman_extrapac.mp3")
export const SOUND_PACMAN_INTERMISSION = new AudioClip("sounds/pacman_intermission.mp3")
